### ISSUE TITLE
Issues with JavaDoesUSB in Windows 11 with USB 1.1 device

### ISSUE THREAD

**Issue by aosocorro** [manuelbl/JavaDoesUSB#15]
Hi @manuelbl 

First of all, great work! The library is amazing and it comes really useful when other USB libraries for Java are almost dead... kudos for that!

I am testing the library for an application which is using a USB 1.1 device on Mac & Windows, and I am finding some issues in the Windows 11 side (in Mac everything works smoothly):

JavaDoesUSB version: 0.5.1

1. Only a specific version of WinUSB seem to work. When I configure the USB data interface of the device with Zadig, the tool shows the following screen, instructing me to downgrade WinUSB:

![image](https://github.com/manuelbl/JavaDoesUSB/assets/119880854/69799e1e-e55a-401a-ba75-8b3f6ac5df51)

I guess this is caused because of the device implementing USB 1.1 (that is the reason WCID does not work with the dongle) ...  do you think I am right? 

2. Once the USB driver is properly set, the application I am testing can be used. I am sending a command to the device with the following code (kotlin syntax):
```kotlin
companion object {
        const val APP_INTERFACE = 4
        const val IN_ENDPOINT = 4
        const val OUT_ENDPOINT = 5
        const val COMMAND = "COMMAND"
 }
device.get()?.apply {
                try {
                    open()
                    claimInterface(APP_INTERFACE) 
                    transferOut(OUT_ENDPOINT, COMMAND.toByteArray())
                } catch (t: Throwable) {
                    logger.error("Unable to execute USB operation ", t)
                } finally {
                    if (isOpen) {
                        if (getInterface(APP_INTERFACE).isClaimed) {
                            releaseInterface(APP_INTERFACE)
                        }
                        logger.debug { "Closing device..." }
                        close()
                    }
                }
            }
```
The code is executed inside a process which is continuously running. As you can see it is pretty straightforward, but its behaviour is weird:

- At first, it does send the command.
- When I remove the device  from the USB connector, and add it again (and I repeat the plug out/plug in process several times), sometimes after plugging the device in, I found the following exception (WinUSB is properly set, as explained above):
```
net.codecrete.usb.USBException: Interface number 4 cannot be claimed (non WinUSB device?)
at net.codecrete.usb.windows.WindowsUSBException.throwException(WindowsUSBException.java:65)
at net.codecrete.usb.windows.WindowsUSBDevice.claimInterface(WindowsUSBDevice.java:114)
...
```
If I remove the device and plug it in again, the command works.

- In all instances, if I run the bulk_transfer example (configured for the device I am testing) from the JavaDoesUSB library, when the long running process fails, the bulk transfer one works properly

Do you think if this is related with the library or with the dongle specification? Would there be any procedure that could help me to debug the issue?

if you think that there is some work that could help with this, just let me know. I would be happy to help.

Again, great work!

Thanks,
Alberto.

**Comment by manuelbl** [comment]
And what error do you get or what happens if you run your code without downgrading the WinUSB driver?

**Comment by aosocorro** [comment]
Thanks for the quick answer @manuelbl. I add some clarifications:

- If WinUSB driver is not downgraded, the device does never work. Neither with my code, nor with the bulk_transfer example.
- The "Interface number 4 cannot be claimed" happens as follows (the USB command is invoked from a graphical interface):
  - The program starts and everything runs fine, the command is invoked and it works.
  - After plugging out and plugging in the device, sometimes the error appears. It is not fixed with time, if it is tested several minutes later, the error still happens, so it is not a timing issue in this case. The workaround is plugging out / plugging in the device: command works again after that. 
  - I would like to remark that this error does not happen all the time; and in the "cycle" when the problem manifest itself, if I run the bulk_transfer example, it does work. So, it would look like some kind of issue with the state inside the library.
- The device is being developed by other group inside my company. 
-  The other interfaces of the device are for audio and HID. This is the result of the enumerate:
```
VID: 0x248a
  PID: 0x881c
  Manufacturer:  CD
  Product name:  Merlyn Mind GO
  Serial number: RF427C
  Device class:    0x00 ((Defined at Interface level))
  Device subclass: 0x00
  Device protocol: 0x00
  Interface 0
    Interface class:    0x01 (Audio)
    Interface subclass: 0x01
    Interface protocol: 0x00
  Interface 1
    Interface class:    0x01 (Audio)
    Interface subclass: 0x02
    Interface protocol: 0x00
  Interface 1 (alternate 1)
    Interface class:    0x01 (Audio)
    Interface subclass: 0x02
    Interface protocol: 0x00
    Endpoint 7
        Direction: IN
        Transfer type: ISOCHRONOUS
        Packet size: 32 bytes
  Interface 2
    Interface class:    0x03 (Human Interface Device)
    Interface subclass: 0x01 (Keyboard)
    Interface protocol: 0x01 (Keyboard)
    Endpoint 1
        Direction: IN
        Transfer type: INTERRUPT
        Packet size: 8 bytes
  Interface 3
    Interface class:    0x03 (Human Interface Device)
    Interface subclass: 0x01 (Mouse)
    Interface protocol: 0x02 (Mouse)
    Endpoint 2
        Direction: IN
        Transfer type: INTERRUPT
        Packet size: 8 bytes
  Interface 4
    Interface class:    0xfe (Application Specific Interface)
    Interface subclass: 0x01
    Interface protocol: 0x01
    Endpoint 4
        Direction: IN
        Transfer type: BULK
        Packet size: 64 bytes
    Endpoint 5
        Direction: OUT
        Transfer type: BULK
        Packet size: 64 bytes
```
- Zadig output for other interfaces is the pretty similar to the one attached in my first comment: the only difference is the driver used (usbaudio for audio interfaces, HidUsb for HID interface). In all cases it suggests to downgrade to WinUSB 6, as it happens with the interface 4 (those interfaces work properly with drivers used by OS)

**Comment by manuelbl** [comment]
Thank you very much fo the information.

In the meantime, I've figured out that the missing information leading to the "Interface number 4 cannot be claimed" error are queried when the device is plugged in, not when the device is opened by the software. So chances are that it is a timing error. My questions regarding whether the device is immediately opened after plug-in thus were misleading.

The fact that the bulk_transfer example always works could be due to the fact that it is only used with devices that have already been plugged in when the software starts and not at a later stage.

I will study it some more and likely publish an updated version. It will require JDK 21, which will be released early next week. I hope that's not a problem for you.

You wrote: "If WinUSB driver is not downgraded, the device does never work." What exactly happens? Is the device invisible? Does an error occur? If so, what error?

If I can, I would really like to get the library to the point where it just works if the device implements WCID or Microsoft OS 2.0 Descriptors. Zadig can be very helpful; but at the end of the day, it's still a workaround for hardware and/or software that wasn't implemented properly.

**Comment by aosocorro** [comment]
If WinUSB driver is not downgraded, the error is (again) : `Interface number 4 cannot be claimed (non WinUSB device?)` on every test. Downgrade of WinUSB is mandatory to make the device working.

Moving to JDK 21 is ok.

**Comment by aosocorro** [comment]
@manuelbl I have seen there is a new version `0.6.0`. Does it contain the fixed you mentioned in your previous comments? or should I wait for `0.6.1` version?

**Comment by manuelbl** [comment]
@aosocorro Version 0.6.0 contains fixes but I'm afraid it won't fully fix your problem as I cannot correctly reproduce it. Thus I would like to build a device with the same configuration as yours.

Can you run the [enumerate](https://github.com/manuelbl/JavaDoesUSB/tree/main/examples/enumerate) example again and send me the output related to your device (using JDK 21 and library version 0.6.0). It now dumps the full device and configuration descriptors. That's the additional part I'm interested in.

Can you also run your software with the new version and try to trigger the problem again? The library now writes additional log information. I'm interested whether there is a difference in the log information when you plug in the device and it works correctly vs. when you plug it in and fails when claiming the interface.

Make sure you get the log information at DEBUG level. If you are using a logging library, make sure it also connects to `System.Logger`. Some libraries need an additional Maven package to do so.

**Comment by aosocorro** [comment]
@manuelbl Logs with some scenario where a USB command works and one failure. To generate the failure, I have had to plug the device in few seconds after the laptop is awaken after being idle:

```
// App is started. USB device is plugged in at this time. Command (buzz) works
2023-09-21 20:55:14.036 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:55:14.065 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:55:14.066 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:55:14.066 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:55:14.084 [main] INFO  o.m.d.c.usb.impl.USBProviderImpl - Found USB paired device. Attaching: RF427C
2023-09-21 20:55:37.857 [JavaFX Application Thread] INFO  BuzzRemote - RCU service invoked to buzz remote

// Unplug and plug. Command continues working
2023-09-21 20:56:01.067 [DefaultDispatcher-worker-7] INFO  o.m.d.c.usb.impl.USBProviderImpl - Not found USB paired device. Detaching...
2023-09-21 20:56:04.695 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Sleeping for 200ms (after unsuccessfully retrieving DEVPKEY_Device_Children)
2023-09-21 20:56:04.898 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:56:04.899 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:56:04.900 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-21 20:56:04.910 [DefaultDispatcher-worker-22] INFO  o.m.d.c.usb.impl.USBProviderImpl - Found USB paired device. Attaching: RF427C
2023-09-21 20:56:22.911 [JavaFX Application Thread] INFO  BuzzRemote - RCU service invoked to buzz remote

// Laptop is becoming idle. Last application log happened at 2023-09-21 20:56:51.916
2023-09-21 20:56:40.021 [DefaultDispatcher-worker-17] INFO  o.m.d.c.usb.impl.USBProviderImpl - Not found USB paired device. Detaching...

// Laptop is awaken the following day at 2023-09-22 09:47:30.517. USB device is plugged in some seconds later. Command does not work 
2023-09-22 09:47:35.204 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 09:47:36.104 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 09:47:36.114 [DefaultDispatcher-worker-20] INFO  o.m.d.c.usb.impl.USBProviderImpl - Found USB paired device. Attaching: RF427C
2023-09-22 09:47:56.285 [JavaFX Application Thread] INFO  BuzzRemote - RCU service invoked to buzz remote
2023-09-22 09:47:56.285 [DefaultDispatcher-worker-6] ERROR o.m.d.c.usb.impl.USBProviderImpl - Unable to execute USB operation 
net.codecrete.usb.USBException: interface number 4 cannot be claimed (non WinUSB device?)
	at net.codecrete.usb.windows.WindowsUSBException.throwException(WindowsUSBException.java:65)
	at net.codecrete.usb.windows.WindowsUSBDevice.claimInterface(WindowsUSBDevice.java:119)
	at org.merlyn.desktopapp.coresdk.usb.impl.USBProviderImpl.executeOperation(USBProviderImpl.kt:124)
	at org.merlyn.desktopapp.coresdk.usb.impl.USBProviderImpl.access$executeOperation(USBProviderImpl.kt:21)
	at org.merlyn.desktopapp.coresdk.usb.impl.USBProviderImpl$buzzRemote$1.invokeSuspend(USBProviderImpl.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2023-09-22 09:48:18.166 [DefaultDispatcher-worker-19] ERROR o.m.d.c.usb.impl.USBProviderImpl - Unable to execute USB operation 
net.codecrete.usb.USBException: interface number 4 cannot be claimed (non WinUSB device?)
	at net.codecrete.usb.windows.WindowsUSBException.throwException(WindowsUSBException.java:65)
	at net.codecrete.usb.windows.WindowsUSBDevice.claimInterface(WindowsUSBDevice.java:119)
	at org.merlyn.desktopapp.coresdk.usb.impl.USBProviderImpl.executeOperation(USBProviderImpl.kt:124)
	at org.merlyn.desktopapp.coresdk.usb.impl.USBProviderImpl.access$executeOperation(USBProviderImpl.kt:21)
	at org.merlyn.desktopapp.coresdk.usb.impl.USBProviderImpl$buzzRemote$1.invokeSuspend(USBProviderImpl.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

// Unplug and plug. Command works again
2023-09-22 09:55:25.840 [DefaultDispatcher-worker-5] INFO  o.m.d.c.usb.impl.USBProviderImpl - Not found USB paired device. Detaching...
2023-09-22 09:55:29.803 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Sleeping for 200ms (after unsuccessfully retrieving DEVPKEY_Device_Children)
2023-09-22 09:55:30.009 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 09:55:30.010 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 09:55:30.011 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 09:55:30.027 [DefaultDispatcher-worker-8] INFO  o.m.d.c.usb.impl.USBProviderImpl - Found USB paired device. Attaching: RF427C
2023-09-22 09:55:37.767 [JavaFX Application Thread] INFO  BuzzRemote - RCU service invoked to buzz remote
2023-09-22 10:12:50.362 [JavaFX Application Thread] INFO  BuzzRemote - RCU service invoked to buzz remote

// Unplug and plug. Command continues working
2023-09-22 10:21:41.737 [DefaultDispatcher-worker-12] INFO  o.m.d.c.usb.impl.USBProviderImpl - Not found USB paired device. Detaching...
2023-09-22 10:21:46.368 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Sleeping for 200ms (after unsuccessfully retrieving DEVPKEY_Device_Children)
2023-09-22 10:21:46.572 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 10:21:46.573 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 10:21:46.574 [USB device monitor] DEBUG n.c.u.w.WindowsUSBDeviceRegistry - Child device {0} has no device path
2023-09-22 10:21:46.585 [DefaultDispatcher-worker-3] INFO  o.m.d.c.usb.impl.USBProviderImpl - Found USB paired device. Attaching: RF427C
2023-09-22 10:21:50.202 [JavaFX Application Thread] INFO  BuzzRemote - RCU service invoked to buzz remote
```

It seems that when claiming interface fails, there is one `Child device {0} has no device path` trace less than when it works; and the log  `Sleeping for 200ms (after unsuccessfully retrieving DEVPKEY_Device_Children)` is missing when claiming interface fails.

**Comment by manuelbl** [comment]
@aosocorro Thank you for the additional information. I can reproduce the problem related to disconnecting and connecting the device. And I have a prototypic fix in C++, which I will now apply to Java with some enhancements. 

Regarding WCID: I‘m surprised to learn that it only works if the USB version is declared as 2.00 or higher (as you already mentioned). So I wonder: how did you install the WinUSB v10 driver? It didn’t happen automatically when you plugged in the device, did it?

**Comment by aosocorro** [comment]
@manuelbl Those are great news! Looking forward to testing the new version when ready. Thanks!

About how to install WinUSB v10 driver, it has to be installed using Device Manager tool. The device is handled as  “Other device”, and [this procedure](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-installation#installing-winusb-by-specifying-the-system-provided-device-class) is followed to let Windows install its “default” WinUSB version (which is v10 in Windows 11 and requires downgrading for my device, as mentioned)

It would be fantastic if JavaDoesUSB could somehow to automate this process for this kind of device. But maybe there are not so many devices like this to make the effort worthy (to say nothing about its complexity)…

**Comment by manuelbl** [comment]
The code now includes a fix for dealing with composite devices on Windows when they are plugged in and Windows discovers the subdevices one by one. You can wait for the official release (probably early next week). Or you can try the snapshot:

```
cd java-does-usb
mvn install -DskipTests
```

Then you need to change your project to use version `0.6.1-SNAPSHOT`.

Independent of this fix: In order to automatically install the WinUSB driver, the device needs to implement *Microsoft OS Compatibility Descriptors 2.0*.  As far as I can tell, the older 1.0 version (aka WCID) does not work for composite devices (and your device is a composite device). All other options include manual installation steps. The options are:

- providing an INF file
- using Zadig

I have tested the [procedure](https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/winusb-installation#installing-winusb-by-specifying-the-system-provided-device-class) you have linked to. It didn't work. I've debugged it and found that the reason is that `SetupDiOpenDevRegKey` returns a registry key at `CurrentControlSet001`while the description refers to `CurrentControlSet`. So the GUID in `DeviceInterfaceGUIDs` is not found. This might be a change from earlier Windows version. But the function `SetupDiOpenDevRegKey` is likely authoritative and returns what the operation system actually uses.

The reason Zadig works is not because the older WinUSB driver is better. It is because the Zadig installation procedure creates the correct registry keys. Zadig would achieve the same with the latest driver. But it can only install the version bundled with itself, and that is version 6.1.

**Comment by manuelbl** [comment]
Release 0.6.1 with the fixes for this issue has been published

**Comment by aosocorro** [comment]
Thanks! 
I will test it and I will close the issue once verified

**Comment by aosocorro** [comment]
Tested successfully. Closing issue
