### ISSUE TITLE
Can't silence an Exception

### ISSUE THREAD

**Issue by icemagno** [manuelbl/JavaDoesUSB#25]
I'm doing this (basicaly your example):

```
		try {
	            for ( var device : Usb.getDevices() ) printDetails(device, "CONNECTED");
	            Usb.setOnDeviceConnected(device -> printDetails(device, "CONNECTED"));
	            Usb.setOnDeviceDisconnected(device -> printDetails(device, "DISCONNECTED"));
		} catch( Throwable t ) {
			// PLEASE BE QUIET !!
		}
```

and getting this error not relevant to what I'm doing but very annoying because It's scaring my users:

```
java.lang.IllegalStateException: Segment size is not a multiple of 2. Size: 7
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkArraySize(AbstractMemorySegmentImpl.java:392)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.toArray(AbstractMemorySegmentImpl.java:352)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.toArray(AbstractMemorySegmentImpl.java:328)
	at net.codecrete.usb.usbstandard.StringDescriptor.string(StringDescriptor.java:35)
	at net.codecrete.usb.windows.WindowsUsbDeviceRegistry.getStringDescriptor(WindowsUsbDeviceRegistry.java:292)
	at net.codecrete.usb.windows.WindowsUsbDeviceRegistry.lambda$createDevice$2(WindowsUsbDeviceRegistry.java:228)
	at net.codecrete.usb.common.UsbDeviceImpl.setProductString(UsbDeviceImpl.java:215)
	at net.codecrete.usb.windows.WindowsUsbDeviceRegistry.createDevice(WindowsUsbDeviceRegistry.java:228)
	at net.codecrete.usb.windows.WindowsUsbDeviceRegistry.createDeviceFromDeviceInfo(WindowsUsbDeviceRegistry.java:191)
	at net.codecrete.usb.windows.WindowsUsbDeviceRegistry.enumeratePresentDevices(WindowsUsbDeviceRegistry.java:160)
	at net.codecrete.usb.windows.WindowsUsbDeviceRegistry.monitorDevices(WindowsUsbDeviceRegistry.java:123)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

I think this is a webcam ( I have one but it was not listed so I think it is the responsible for this ). This error don't broke my executions but is very annoying.

Webcam Multilaser Wc055

Already tried to surround with any Try..Catch possible but it still throwing... What can I do to solve this?

**Comment by manuelbl** [comment]
Thanks for reporting this. It looks as if the device returns an invalid string descriptor (since the descriptor is in UTF-16, it would need to contain an even number of bytes but doesn't). I will probably change the code to make it slightly more robust.

The exception is thrown and printed in a background thread. So your exception handlers have no effect. The exception is printed using the Java system logger (see https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/System.Logger.html). So if you want to hide it, it's probably best the use a logging library that can consume these log messages and configure it such that it is not printed.

**Comment by icemagno** [comment]
Thanks. Do you know what class I must suppress in my Logback XML ? Perhaps ```jdk.internal.foreign.AbstractMemorySegmentImpl.checkArraySize```

**Comment by manuelbl** [comment]
The class to suppress is `net.codecrete.usb.windows.WindowsUsbDeviceRegistry`.

**Comment by icemagno** [comment]
Thanks. Closing.

**Comment by difasanditya** [comment]
> It looks as if the device returns an invalid string descriptor (since the descriptor is in UTF-16, it would need to contain an even number of bytes but doesn't). I will probably change the code to make it slightly more robust.

Hi @manuelbl, I also encounter the same error, but I had to actually use the ignored device. Is there any progress on this issue or should I open a new issue? Gladly to help fix the issue too if you can point me to where and what to check

**Comment by manuelbl** [comment]
Several issues related to invalid string descriptors are now ignored. But I've missed this one. I will look into it.

**Comment by manuelbl** [comment]
@difasanditya I've pushed a fix to the main branch. If you don't mind building a snapshot release, you can do so:

```
cd java-does-usb
mvn clean install -DskipTests
```

I would appreciate any feedback.

**Comment by difasanditya** [comment]
Hi, @manuelbl! Sorry for the late response.

I just pulled the main branch and tested it. Now it can recognize my device without any error. Will try transferring data later, so far looking good.

Thanks for the help! Looking forward for the released version.
